name: David Angell - Audio Production Portal
favicon: null
layout_spectrum: 1
typography_spectrum: 0.79688
title: David Angell - Audio Production Portal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f3d6f'
    - '#5484c2'
    - '#0d1627'
    - '#caaf9c'
    - '#addffc'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
