name: David Angell - Audio Production Portal
favicon: null
layout_spectrum: 0.17256
typography_spectrum: 0.79688
title: David Angell - Audio Production Portal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8dfe9'
    - '#1f221f'
    - '#535049'
    - '#a89f8c'
    - '#868475'
  brandStrength: 0.4375
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
